In [2]:
import numpy as np

In [3]:
arr = np.array([[5,5,8,9], [8,6,9,40]])
print(arr)

[[ 5  5  8  9]
 [ 8  6  9 40]]


In [4]:
z= np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
one = np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
f = np.full((8,8),10)
print(f)

[[10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]]


In [7]:
e = np.eye(5)
print(e)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
i = 10
ar = np.arange(1,100,i+2)
print(ar)

[ 1 13 25 37 49 61 73 85 97]


In [9]:
ls =np.linspace(1,100,5)
print(ls)

[  1.    25.75  50.5   75.25 100.  ]


# slicing

In [10]:
arr = np.array([[4,5,7,8],[6,8,9,4],[6,3,6,8]])
print(arr)


[[4 5 7 8]
 [6 8 9 4]
 [6 3 6 8]]


In [11]:
arr.reshape(6,2)

array([[4, 5],
       [7, 8],
       [6, 8],
       [9, 4],
       [6, 3],
       [6, 8]])

In [12]:
flat = arr.flatten()
flat

array([4, 5, 7, 8, 6, 8, 9, 4, 6, 3, 6, 8])

In [13]:
flat

array([4, 5, 7, 8, 6, 8, 9, 4, 6, 3, 6, 8])

In [14]:
b = flat[5 :9].copy()
b

array([8, 9, 4, 6])

In [15]:
b[2] = 58555
b

array([    8,     9, 58555,     6])

In [16]:
flat

array([4, 5, 7, 8, 6, 8, 9, 4, 6, 3, 6, 8])

In [17]:
a = flat[[5,7,9]]
a

array([8, 4, 3])

In [18]:
flat

array([4, 5, 7, 8, 6, 8, 9, 4, 6, 3, 6, 8])

In [19]:
flat[flat>8]

array([9])

# Multidimensional Indexing and Axis



In [20]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
arr[1, 2] =9999
arr

array([[   1,    2,    3],
       [   4,    5, 9999],
       [   7,    8,    9]])

In [22]:
arr = arr.flatten()
arr[1] =909
arr

array([   1,  909,    3,    4,    5, 9999,    7,    8,    9])

In [23]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr

array([   1,  909,    3,    4,    5, 9999,    7,    8,    9])

# Broadcasting in NumPy